-- seed.sql — local-only dev seed.
--
-- Reference data (official orgs + starter threat taxonomy) now lives in a versioned
-- migration so it ships to every environment: supabase/migrations/0005_reference_data.sql.
-- Add throwaway local-only fixtures here if needed; keep production reference data
-- in migrations.
