/**
 * PLACEHOLDER — regenerated by `npm run db:types`
 * (supabase gen types typescript --local > src/types/database.types.ts).
 *
 * This minimal shape lets the app typecheck before the local DB is introspected.
 * This file IS committed (so CI and fresh clones typecheck without a running DB).
 * Don't hand-edit beyond this stub — run `npm run db:types` and commit the result.
 */
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
